from typing import TypedDict


class AgentState(TypedDict):
    """
    State definition for the Nutritional AI Agent LangGraph workflow.
    
    Attributes:
        age (int): User age in years.
        weight (float): User weight in kilograms.
        goal (str): Target fitness/health goal.
        dietary_restrictions (str): Any allergies or dietary preferences.
        raw_recipe (str): Unformatted raw output generated by the Extraction Agent.
        formatted_meal_plan (str): Final formatted Markdown recipe plan from the Formatting Agent.
    """
    age: int
    weight: float
    goal: str
    dietary_restrictions: str
    raw_recipe: str
    formatted_meal_plan: str
